---
galaxy_info:
  author: Romain Le Cellier
  description: Common users creation/configuration on server's bootstrap
  license: GPLv3
  min_ansible_version: 1.2
  platforms:
  - name: Debian
    versions:
    - all
  #  - etch
  #  - jessie
  #  - lenny
  #  - squeeze
  #  - wheezy

  categories:
  - system
dependencies: []

