---

# Handlers file for fail2ban
- name: restart fail2ban
  service:
    name  : "{{ fail2ban_service_name }}"
    state : restarted
  when : fail2ban_service_state != "stopped"

- name: reload ufw
  ufw: state=reloaded
  ignore_errors: yes

- name: restart sshd
  service: name=ssh state=restarted

