---

- name: install git repos per user
  git:
    repo={{ item[1].src }}
    dest={{ item[1].dest }}
    depth=1
    accept_hostkey=yes
    version={{ item[1].version }}
  become_user: "{{ item[0].name }}"
  become: no
  with_subelements:
    - "{{ common_users_users|default([]) }}"
    - repos
  tags:
    - usermanagement

- name: Set correct ownership for personal git repos
  file: name={{ item[1].dest }}
        owner={{ item[0].name }}
        group={{ item[0].name }}
        recurse=yes
  with_subelements:
    - "{{ common_users_users|default([]) }}"
    - repos
  tags:
    - usermanagement

- name: Execute installers for users
  command: "{{ item[1].command }}"
  become: yes
  become_user: "{{ item[0].name }}"
  with_subelements:
    - "{{ common_users_users|default([]) }}"
    - installers
  tags:
    - usermanagement
