---

- name: Add common groups
  group:
    name={{ item }}
    state=present
  with_items: "{{ common_groups|default([]) }}"

- name: Lookup for existing users
  action: shell /usr/bin/getent passwd {{ item.name }} | /usr/bin/wc -l | tr -d ' '
  register: users_exists
  changed_when: false
  with_items: "{{ users|default([]) }}"

- name: Add users (if not already exists)
  user:
    name={{ item.1.name }}
    comment="{{ item.1.comment }}"
    shell={{ item.1.shell }}
    append=yes
    groups={{ ",".join(item.1.groups) }}
    state=present
  when: "{{ users_exists.results[item[0]].stdout }} != 1"
  with_indexed_items: "{{ users|default([]) }}"

- name: Add public SSH authorized keys per user
  authorized_key:
    user={{ item[0].name }}
    key="{{ item[1] }}"
  with_subelements:
    - "{{ users|default([]) }}"
    - ssh_key

- name: Allow passwordless sudo for sudo users
  lineinfile:
    "dest=/etc/sudoers
    state=present
    regexp='^{{ item }}'
    insertafter=EOF
    line='{{ item }} ALL=(ALL) NOPASSWD: ALL'"
  with_items: "{{ sudo_users|default([]) }}"

