---

- name: Add common groups
  group:
    name={{ item }}
    state=present
  with_items: "{{ groups|default([]) }}"

- name: Add users
  user:
    name={{ item.name }}
    comment="{{ item.comment }}"
    shell={{ item.shell }}
    groups={{ ",".join(item.groups) }}
    state=present
  with_items: "{{ users|default([]) }}"

- name: Add public SSH authorized keys per user
  authorized_key:
    user={{ item[0].name }}
    key="{{ item[1] }}"
  with_subelements:
    - "{{ users|default([]) }}"
    - ssh_key

- name: Allow passwordless sudo for sudo users
  lineinfile:
    "dest=/etc/sudoers
    state=present
    regexp='^{{ item }}'
    insertafter=EOF
    line='{{ item }} ALL=(ALL) NOPASSWD: ALL'"
  with_items: "{{ sudo_users|default([]) }}"

