---
galaxy_info:
  author: Romain Le Cellier
  description: Common configuration
  license: GPLv3
  min_ansible_version: 1.2
  platforms:
  - name: Debian
    versions:
    - all
  categories:
  - system
dependencies: []

