---
# tasks file for bootstrap
- name: Remove unwanted packages
  apt:
    name={{ item }}
    force=yes
    purge=yes
    state=absent
  with_items: "{{ common_apt_packages_remove|default([]) }}"

- name: Update packages
  apt:
    update_cache=yes
    upgrade=dist
    cache_valid_time=86400
  tags:
    - apt-update

- name: Install common packages
  apt:
    name={{ item }}
    update_cache=yes
    cache_valid_time=86400
    install-recommends=no
    state=present
  with_items: "{{ common_apt_packages|default([]) }}"

- name: Install common pip packages
  pip:
    name={{ item }}
    state=present
  with_items: "{{ common_apt_pip_packages|default([]) }}"
