---
check_mode: true

# fail2ban default vars
fail2ban_package_state: present
fail2ban_packages :
  - fail2ban

# Service variables
#------------------
fail2ban_service_name: fail2ban
fail2ban_service_state: started
fail2ban_service_enabled: True

fail2ban_loglevel: 3
fail2ban_logtarget: /var/log/fail2ban.log
fail2ban_syslog_target: /var/log/fail2ban.log
fail2ban_syslog_facility: 1
fail2ban_socket: /var/run/fail2ban/fail2ban.sock
fail2ban_pidfile: /var/run/fail2ban/fail2ban.pid

fail2ban_ignoreips:
  - 127.0.0.1/8

# 3 days
fail2ban_bantime: 259200
fail2ban_maxretry: 5
# one houre
fail2ban_findtime: 3600
fail2ban_backend: auto
fail2ban_destemail: name@host.tld
fail2ban_banaction: iptables-multiport
fail2ban_mta: sendmail
fail2ban_protocol: tcp
fail2ban_chain: INPUT
fail2ban_action: action_

fail2ban_services:
  - name: ssh
    enabled: true
    port: ssh
    filter: sshd
    logpath: /var/log/auth.log
    maxretry: 4
    # one houre
    findtime: 3600

